services:
  backend:
    build: backend
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/app/src:ro
      - ./backend/data/music_library:/app/data/music_library:rw

  frontend:
    ports:
      - 8080:80
    build: frontend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./backend/data/dbdata:/data/db