services:
  vue-music-backend:
    build: .
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]
    volumes:
      - ./src:/app/src:ro
      - ./data/music_library_streaming:/app/data/music_library_streaming:rw
    ports:
      - 3000:3000

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./data/dbdata:/data/db